name: Terraform Destroy

# Allow the workflow to be triggered manually
on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Run Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Run Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy --auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}} # Replace with your secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
